export {
  NotebookText as LedgerIcon,
  PackageSearch as InventoryIcon,
  Tags as PricesIcon,
  Users as UsersIcon,
  User as ProfileIcon,
  LogOut as SignOutIcon,
  Plus as PlusIcon,
  Search as SearchIcon,
  Edit3 as EditIcon,
  Trash2 as TrashIcon,
  Crown as AdminIcon,
  Lock as LockIcon,
  Unlock as UnlockIcon,
  Bell as BellIcon,
  BellOff as BellOffIcon,
  CheckCircle2 as CheckIcon,
  XCircle as ErrorIcon,
  AlertCircle as AlertIcon,
  Info as InfoIcon,
  Zap as LowStockIcon,
  PackageX as OutOfStockIcon,
  PackageCheck as RestockedIcon,
  Ban as BanIcon,
  ShieldCheck as ShieldIcon,
  Tag as TagIcon,
  Package as PackageIcon,
  UserPlus as UserPlusIcon,
  X as CloseIcon,
} from "lucide-react";

export type { LucideIcon as IconComponent } from "lucide-react";
